#!/bin/bash

# Check if the first argument is -v or --verbose
verbose=0
if [[ $1 == "-v" ]] || [[ $1 == "--verbose" ]]; then
    verbose=1
    # Shift the positional parameters to the left, effectively removing the first argument
    shift
fi

# Define a function for verbose output
function verbose_output {
    if [[ $verbose -eq 1 ]]; then
        echo "$1"
    fi
}

# Set CURRENT_PATH to the current working directory
CURRENT_PATH=$(pwd)
verbose_output "Set CURRENT_PATH to $CURRENT_PATH"

# Switch to the oe-init-build-env directory
pushd $CURRENT_PATH/srcs/poky/
verbose_output "Switched to $(pwd)"

# Source the oe-init-build-env script
source oe-init-build-env
verbose_output "Sourced the oe-init-build-env script"

# Return to the original directory
popd
verbose_output "Returned to $(pwd)"

# Replace all occurrences of "/home/ubuntu/moe/poky" and "/home/ubuntu/poky" with "$CURRENT_PATH/srcs/poky" in patch-bblayers.conf
sed -i "s|/home/ubuntu/moe/poky|$CURRENT_PATH/srcs/poky|g" $CURRENT_PATH/srcs/yocto-scripts/patches/patch-bblayers.conf
sed -i "s|/home/ubuntu/poky|$CURRENT_PATH/srcs/poky|g" $CURRENT_PATH/srcs/yocto-scripts/patches/patch-bblayers.conf
verbose_output "Replaced all occurrences of \"/home/ubuntu/moe/poky\" and \"/home/ubuntu/poky\" with \"$CURRENT_PATH/srcs/poky\" in patch-bblayers.conf"

# Apply patches
for patch in $CURRENT_PATH/srcs/yocto-scripts/patches/patch-*; do
    # Extract the filename from the patch file and remove the "patch-" prefix
    filename=$(basename $patch | sed 's/^patch-//')
    verbose_output "Processing patch file $patch"

    # Apply the patch to the corresponding file in srcs/poky/build/conf/
    patch $CURRENT_PATH/srcs/poky/build/conf/$filename -i $patch
    verbose_output "Applied patch to $CURRENT_PATH/srcs/poky/build/conf/$filename"
done